name: "Publish Neuron site"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@c952173edf28a2bd22e1a4926590c1ac39630461
    - uses: cachix/install-nix-action@ef4324316b96b50b4671cecef9ecc6fd286f224a
    - uses: cachix/cachix-action@6e4751ed42b22f60165d3f266cfa4cce66ae406d
      with:
        name: srid
    - name: Install neuron
      run: nix-env -if https://github.com/srid/neuron/archive/master.tar.gz
    - name: Build neuron site 🔧
      run: |
        neuron --version
        neuron rib
    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .neuron/output
