name: "Publish Neuron site"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@c952173edf28a2bd22e1a4926590c1ac39630461
    - uses: cachix/install-nix-action@95a8068e317b8def9482980abe762f36c77ccc99
    - uses: cachix/cachix-action@490a246fbc7f92208d309eeb54383a4d828cedc1
      with:
        name: srid
    - name: Install neuron 
      run: nix-env -if https://github.com/srid/neuron/archive/master.tar.gz
    - name: Build neuron site 🔧
      run: |
        neuron --version
        neuron rib
    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .neuron/output
